# Generated by Django 5.2.17 on 2026-08-29 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstatushistory',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_status_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
