# Generated by Django 5.2.17 on 2026-09-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_latitude_ticket_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketstatushistory',
            options={'ordering': ['changed_at'], 'verbose_name_plural': 'Ticket status histories'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='longitude',
        ),
    ]
